version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8080"
    volumes:
      - drupal-public-files:/drupal-files/public
      - drupal-private-files:/drupal-files/private
      - drupal-backups:/drupal-files/backups
    environment:
      - DB_NAME=drupal_db
      - DB_USER=dbuser
      - DB_PASSWORD=passw0rd
      - DB_HOST=drupal-database
      - DB_PORT=3306
      - DB_DRIVER=mysql
    links:
      - drupal-database
  drupal-database:
    image: mariadb
    volumes:
      - drupal-db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=drupal_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_PORT=3306
      - MYSQL_RANDOM_ROOT_PASSWORD=true
volumes:
  drupal-public-files:
  drupal-private-files:
  drupal-backups:
  drupal-db-volume: