version: '3'
services:
  web:
    image: giteshk/drupal8-gcp-docker:latest
    ports:
      - "5000:8080"
    volumes:
      - devportal-public-files:/drupal-files/public
      - devportal-private-files:/drupal-files/private
      - devportal-backups:/drupal-files/backups
    environment:
      - DB_NAME=drupal_db
      - DB_USER=dbuser
      - DB_PASSWORD=passw0rd
      - DB_HOST=drupal-database
      - DB_PORT=3306
      - DB_DRIVER=mysql
    links:
      - drupal-database
  drupal-database:
    image: mariadb
    volumes:
      - devportal-db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=drupal_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_PORT=3306
      - MYSQL_RANDOM_ROOT_PASSWORD=true
volumes:
  devportal-public-files:
  devportal-private-files:
  devportal-backups:
  devportal-db-volume: